# Test config file for reading Chilbolton data

PATH:
  data: /Users/workcset/Library/CloudStorage/OneDrive-UniversityofReading/Code/simple-track/data
  loader: ChilboltonLoader
  output: ./output_chilbolton_oost_test

OUTPUT:
  experiment_name: chilbolton_test
  save_data: true
  save_plots: true
  plot_format: png

DATETIME:
  start_time: 2012-08-25 14:05:00
  time_interval: 5 
  time_interval_tolerance: 15 # Maximum separation in time allowed between consecutive images
  # Should default the above to be 3 * time_interval if not specified

RADAR:
  is_radar: False

FEATURE:
  threshold: 3 ## Threshold used to identify objects (with value of variable greater than this threshold)
  under_threshold: false ## True = labelling areas *under* the threshold (e.g. brightness temperature), False = labelling areas *above* threshold (e.g. rainfall)
  min_size: 4 # Minimum size of feature to be tracked (in pixels)

OF_SOLVER:
  overlap_threshold: 0.6 ## Minimum fraction of overlap (0.6 in TITAN)
  # subdomain_size: 100 ## Size in pixels of individual squares to run fft for (dx,dy) displacement. Must divide (x,y) lengths of the array!
  min_fractional_coverage: 0.01  ## Minimum fractional cover of objects required for fft to obtain (dx,dy) displacement
  subdomain_tolerance: 3.0  # Maximum difference in displacement values between adjacent squares (to remove spurious values) - scaled by num_dt if necessary
  apply_tukey_filtering: True

TRACKING:
  overlap_nbhood: 2 ## Radius of halo in pixels for orphan storms - big halo assumes storms may spawn "children" at a distance multiple pixels away
  overlap_threshold: 0.4 ## Minimum fraction of overlap (0.6 in TITAN)
  retain_lifetime_on_split: True